### ISSUE TITLE
[DOCS] update docker compose command

### ISSUE THREAD

**Issue by Ananya2001-an** [Ananya2001-an/DevOps#3]
**Which doc needs updating and why?**
In docker/README.md we have the docker compose section where we must update the docker compose command from `docker-compose` to `docker compose`. Basically remove the hyphen. This is necessary since soon by June'23 the docker compose V1 won't be used anymore. So everyone has to install and use V2 from now on. 

![image](https://user-images.githubusercontent.com/55504616/224480955-8e34fda3-7845-4b86-b9fe-93c7ac621c16.png)

**Comment by gulshan2052** [comment]
@Ananya2001-an I would like to work on this, please assign it to me.

**Comment by Ananya2001-an** [comment]
Sure go ahead!

**Comment by gulshan2052** [comment]
@Ananya2001-an Should i edit the image as well?
![image](https://user-images.githubusercontent.com/73067659/226885703-196ef064-4dfa-49ae-bf14-4907446a094c.png)

**Comment by Ananya2001-an** [comment]
Yeah that would be good!
